version: '3'
services:
  postgresql:
    image: postgres:14.0-alpine
    container_name: bookshelf
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always